### ISSUE TITLE
¿de dónde sale bootstrap?

### ISSUE THREAD

**Issue by RafaelGilVelarde** [ulima-pw/help_20212#20]

**Comment by billygl** [comment]
Para agregar bootstrap al proyecto

- ir a https://getbootstrap.com/
- clic en **Download** 
  ![image](https://user-images.githubusercontent.com/442925/132601025-bbb5caa0-f561-4b00-91f0-e41de305ca90.png)
- ir hasta la parte inferior
  ![image](https://user-images.githubusercontent.com/442925/132601086-1954195d-0534-48e3-81e8-a653e03b1ecf.png)
- copiar
  ````
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  ````
- agregar en el head del archivo html
  ![image](https://user-images.githubusercontent.com/442925/132601198-2cd89ff3-e3d5-4138-a802-b1045d952f6c.png)
