### ISSUE TITLE
error para iniciar el servidor 

### ISSUE THREAD

**Issue by AlonsoCPG20** [ulima-pw/help_20212#23]
![problema](https://user-images.githubusercontent.com/79822714/137823904-b8fa9158-68cb-45ea-966a-f36366fdd71d.PNG)
![instalacion init](https://user-images.githubusercontent.com/79822714/137823917-ab7a043e-2370-496d-a15f-65aa68923865.PNG)
![instalacion express](https://user-images.githubusercontent.com/79822714/137823940-6ca04eeb-e0df-41d0-bd46-d8a447ff9005.PNG)

**Comment by billygl** [comment]
# problema
- nombre con mayúsculas

# solución
- usar solo minúsculas
- se puede cambiar el nombre directamente en el package.json

# nota
- la segunda pantalla y la tercera no son errores. 
- La segunda es el resultado de ejecutar el comando y la tercera además de eso muestra unos warnings que por ahora lo ignoraremos
