### ISSUE TITLE
Uso de .scss para proyecto final

### ISSUE THREAD

**Issue by cristianmurrieta** [ulima-pw/help_20212#25]
Buenas Billy una consulta, quería saber si no habría problema para usar .scss en el trabajo final? Gracias de antemano

**Comment by billygl** [comment]
si todo el grupo conoce cómo trabajar, no habría problema. Pero todos podrían ser preguntados al respecto.
Consúltalo con tu grupo si están dispuestos a ello. 
La idea es que ninguno se perjudique.
