### ISSUE TITLE
no puedo configurar la base de datos

### ISSUE THREAD

**Issue by Gsushimabuko** [ulima-pw/help_20212#26]
Bajé el postgres, pero olvide mi contraseña. Lo desinstalé y lo volví a reinstalar (en una versión anterior 13.algo) y setee una nueva contraseña (no sé si esto tenga que ver con el problema).

![imagen](https://user-images.githubusercontent.com/86267995/140855464-26e3cf29-a026-465b-be46-82b889593c40.png)

**Comment by Gsushimabuko** [comment]
Solucionado! edité el pg_hba usando un tutorial de yt jajaja

**Comment by billygl** [comment]
Como cambiar el password en PostgreSQL #PostgreSQL Consejos | Trucos
https://www.youtube.com/watch?v=sRMcWWzR714
